# Generated by Django 4.1.2 on 2022-12-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clients",
            old_name="username",
            new_name="client",
        ),
    ]
