# Generated by Django 4.1.2 on 2022-11-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clients",
            name="slug",
        ),
    ]
