# Generated by Django 4.1.2 on 2022-11-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_clients_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="phone",
            field=models.TextField(
                blank=True, max_length=250, null=True, verbose_name="Телефон"
            ),
        ),
        migrations.AlterField(
            model_name="clients",
            name="question",
            field=models.TextField(
                blank=True, max_length=250, null=True, verbose_name="Текст питання"
            ),
        ),
    ]
